name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'  # Using 1.22 as 1.25 is not yet released

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run vet
        run: go vet ./...

      - name: Build binaries
        run: |
          mkdir -p bin
          go build -v -ldflags="-s -w" -o bin/cpusim-server ./cmd/cpusim-server
          go build -v -ldflags="-s -w" -o bin/collector-server ./collector/cmd/collector-server

      - name: Check binaries
        run: |
          ls -lah bin/
          file bin/cpusim-server
          file bin/collector-server

      - name: Test collector API generation
        run: |
          go generate ./...
          # Check if generated files are up to date
          git diff --exit-code || (echo "Generated files are not up to date. Run 'go generate ./...' and commit the changes." && exit 1)

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ github.sha }}
          path: bin/
          retention-days: 7